#!/usr/bin/env python3
"""Embed trusted wap runtime for filesystem-free compilation. --check is read-only."""
from pathlib import Path
import sys
import re

root = Path(__file__).resolve().parent.parent
source = (root / "wisp/runtime.wap").read_text()
generated = "// Generated by tools/gen-wisp-runtime.py; edit runtime.wap.\n///|\nlet runtime_source : String =\n" + "\n".join("  #|" + line for line in source.splitlines()) + "\n"
# Only the persistent half is trusted by Wisp. Inline its three numeric
# constants so the resulting Wasm has no globals, even for runtime constants.
vector = (root / "stdlib-wap/collections/persistent_vector.wap").read_text().split("pub type transient =")[0]
for name, value in re.findall(r"^const (\w+) = (\d+)$", vector, re.M):
    vector = re.sub(r"^const " + name + r" = \d+\n", "", vector, flags=re.M)
    vector = re.sub(r"\b" + name + r"\b", value, vector)
vector = re.sub(r'export "[^"]+" ', '', vector)
generated += "\n///|\nlet vector_source : String =\n" + "\n".join("  #|" + line for line in vector.splitlines()) + "\n"
hamt = (root / "stdlib-wap/collections/persistent_hash_map.wap").read_text().split("pub type transient =")[0]
hamt = re.sub(r'export "[^"]+" ', '', hamt)
generated += "\n///|\nlet map_source : String =\n" + "\n".join("  #|" + line for line in hamt.splitlines()) + "\n"
target = root / "wisp/runtime_generated.mbt"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != generated:
        sys.exit("wisp runtime embed is stale")
else:
    target.write_text(generated)
