#!/usr/bin/env python3
"""Regenerate `wap/stdlib_test.mbt` from the sources in `stdlib-wap/`.

The wap module's own tests compile the ported standard library, which means
those sources have to reach a test that cannot read files -- `moon test` runs
on wasm as well as native. So they are embedded, and embedding them by hand is
how a copy silently stops matching the file it was copied from.

`tools/wapc` compiles the same tree through a filesystem loader and is the
better check of the two; this one exists so that the check also runs where
there is no filesystem, and so that `marianoguerra/wap` carries its own
evidence rather than depending on the development module for it.

Run it after changing anything under `stdlib-wap/`; the diff is the review
artifact, as with every other generated file here.
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "stdlib-wap"
OUT = ROOT / "wap" / "stdlib_test.mbt"

# What each module has to show for itself beyond compiling. These are the
# claims the port is making -- that the module prefix is applied, that a type
# chose the instruction, that an export name survived -- and they are checked
# against the emitted wat.
ASSERTIONS = {
    "collections.hashing": [
        ('w.contains("$hashing__mix_i32")',
         "The module supplies the prefix the .wax file writes by hand."),
        ('w.contains("i32.shr_u")',
         "`u32` chose the logical shift with no `>>u` in the source."),
        ('w.contains("i32.rotl")', None),
        ('w.contains("array.get_u")', None),
    ],
    "collections.persistent_vector": [
        ('w.contains("$persistent_vector__push")', None),
        ('w.contains("\\"pv_empty\\"")',
         "The wasm export name is an ABI and is left alone."),
    ],
    "collections.persistent_hash_map": [
        ('w.contains("$persistent_hash_map__node_assoc")', None),
        ('w.contains("i32.popcnt")', None),
        ('!w.contains("ref.cast (ref $persistent_hash_map__visit)")',
         "A callback reaches `each` without a cast; see the rec-group tests."),
    ],
    "collections.persistent_hash_set": [
        ('w.contains("$persistent_hash_set__union")',
         "The set reaches the map by name rather than by concatenation."),
        ('w.contains("$persistent_hash_map__assoc")', None),
    ],
    "collections.example": [
        ('w.contains("\\"collections_example\\"")', None),
    ],
    "text.utf8": [
        ('w.contains("$utf8__validate")', None),
        ('w.contains("$hashing__bytes_value")',
         "The hash is the one from `collections.hashing`, not a copy of it."),
    ],
    "data.immutable_value": [
        ('w.contains("$jv__equal")',
         "The module is called `jv`, not the file it lives in."),
        ('w.contains("$jv__record_equal")',
         "The three functions that close the loop with `data/record` live here."),
        ('w.contains("$persistent_hash_map__assoc")', None),
    ],
    "data.record": [
        ('w.contains("$record__type_create")', None),
    ],
    "data.example": [
        ('w.contains("\\"immutable_data_example\\"")', None),
    ],
}


def module_paths():
    """Every module in the tree, deepest dependencies first is not needed --
    the loader resolves imports -- but a stable order keeps the diff small."""
    out = []
    for path in sorted(SRC.rglob("*.wap")):
        rel = path.relative_to(SRC).with_suffix("")
        out.append((".".join(rel.parts), path))
    return out


def ident(path):
    return path.replace(".", "_") + "_wap"


def literal(name, text):
    lines = ["///|", "let %s : String =" % name]
    body = text.split("\n")
    # A trailing newline in the file is not part of the literal: the `#|` form
    # joins with newlines, so the last line would otherwise be an empty one.
    if body and body[-1] == "":
        body.pop()
    for line in body:
        lines.append("  #|" + line)
    return "\n".join(lines)


def main():
    mods = module_paths()
    if not mods:
        sys.exit("gen-stdlib-test: no sources under %s" % SRC)
    parts = [
        "// Generated by tools/gen-stdlib-test.py from stdlib-wap/. DO NOT EDIT.",
        "//",
        "// The ported Wax standard library, compiled as the wap module's own",
        "// regression suite. `just wap-stdlib` compiles the same sources from disk",
        "// through a filesystem loader; this is the copy that runs where there is no",
        "// filesystem, which is every backend but native.",
        "",
    ]
    for path, file in mods:
        parts.append(literal(ident(path), file.read_text()))
        parts.append("")

    entries = ",\n    ".join(
        '("%s", %s)' % (path, ident(path)) for path, _ in mods
    )
    parts.append("///|")
    parts.append("/// Every ported module, under the path its importers name it by.")
    parts.append("fn stdlib_loader() -> @resolve.MapLoader {")
    parts.append("  @resolve.MapLoader::new(entries=[")
    parts.append("    " + entries + ",")
    parts.append("  ])")
    parts.append("}")
    parts.append("")
    parts.append("///|")
    parts.append("/// Compile one module, and everything it imports, to wat.")
    parts.append(
        "fn stdlib_wat(path : String, src : String) -> String raise @compile.CompileError {"
    )
    parts.append(
        "  match @wap.compile_program_to_wat(path, src, stdlib_loader()) {"
    )
    parts.append("    Ok(w) => w")
    parts.append("    Err(d) => {")
    parts.append("      let sb = StringBuilder()")
    parts.append('      for r in d.wap {')
    parts.append('        sb.write_string("wap: " + r.message + "\\n")')
    parts.append("      }")
    parts.append("      let sink = @diagnostic.buffer_sink(sb)")
    parts.append("      let theme = @diagnostic.get_theme(is_tty=false)")
    parts.append("      for r in d.wax {")
    parts.append(
        "        @diagnostic.output_error(sink, theme, Human, Some(src), r)"
    )
    parts.append("      }")
    parts.append('      "FAILED\\n" + sb.to_string()')
    parts.append("    }")
    parts.append("  }")
    parts.append("}")
    parts.append("")

    for path, _ in mods:
        name = ident(path)
        parts.append("///|")
        parts.append(
            'test "the %s stdlib module, ported to wap, compiles" {' % path
        )
        parts.append('  let w = stdlib_wat("%s", %s)' % (path, name))
        parts.append('  if w.contains("FAILED") {')
        parts.append("    println(w)")
        parts.append('    fail("%s did not compile")' % path)
        parts.append("  }")
        for expr, note in ASSERTIONS.get(path, []):
            if note:
                parts.append("  // " + note)
            parts.append("  assert_true(%s)" % expr)
        parts.append("}")
        parts.append("")

    OUT.write_text("\n".join(parts).rstrip("\n") + "\n")
    print("gen-stdlib-test: wrote %s (%d modules)" % (OUT.relative_to(ROOT), len(mods)))


if __name__ == "__main__":
    main()
